---
baseurl: "https://fspoettel.github.io/blaupause/"
title: "Blaupause"
enableRobotsTXT: "true"
googleAnalytics: "UA-XXXXXX"
languageCode: "en-us"
layoutdir: '../src/layouts'
metaDataFormat: "yaml"
params:
  AuthorName: "Felix Spöttel"
  AuthorLink: "https://github.com/fspoettel"
---
